apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: coc0r7dyz-go 
  janus-idp.io/tekton: coc0r7dyz-go
  backstage.io/kubernetes-id: coc0r7dyz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: coc0r7dyz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml